language: go

go:
  - '1.11' # Use Golang 1.11

# Specify which branches to build using a safelist
branches:
  only:
    - source

install:
  # install hugo
  - go get github.com/gohugoio/hugo

script:
  # build website
  - hugo

deploy:
  provider: pages # Important, it means using github pages to deploy
  skip-cleanup: true # Important, keep it to true
  local-dir: public # Your content direcotry after building
  target-branch: master # Which branch to push to
  github-token: $GITHUB_TOKEN # Your github access token for travis
  keep-history: true # keep the target-branch history
  on:
    branch: source # source code branch
